# Configuration Base de donnees MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/suivi_academique?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Activer Flyway pour les migrations automatiques
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# JWT
jwt.secret=monSecretSuperSecurisePourLesTokensJWT2026
jwt.expiration=1800000

# SMS (mock pour dev)
sms.provider=mock
sms.api.key=
sms.api.secret=

# Fichiers PDF
pdf.schedules.path=./schedules

# Server
server.port=8080
